source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '4.0.1'

# Core
gem 'bootsnap', '>= 1.18', require: false
gem 'jbuilder'
gem 'pg', '>= 1.5'
gem 'puma', '>= 6.0'
gem 'rack-cors'
gem 'rails', '~> 8.0.4'
gem 'redis'
gem 'sidekiq'
gem 'tzinfo-data', platforms: %i[windows jruby]

# Authentication & Authorization
gem 'cancancan', '~> 3.6'
gem 'devise' # safer than clearance on Rails 8

# Multi-tenancy
gem 'acts_as_tenant'

# Monitoring
gem 'honeybadger'

group :development, :test do
  gem 'dotenv-rails'
  gem 'faker'
  gem 'pry'
end

group :development do
  gem 'letter_opener'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :test do
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end
