source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '4.0.1'

# Core
gem 'bootsnap', '>= 1.18', require: false
gem 'pg', '>= 1.5'
gem 'puma', '>= 6.0'
gem 'rack-cors'
gem 'rails', '~> 8.0.4'
gem 'tzinfo-data', platforms: %i[windows jruby]

# Authentication & Authorization
gem 'cancancan', '~> 3.6'
gem 'devise'

# Multi-tenancy
gem 'acts_as_tenant'

# Additional gems
gem 'jsonapi-serializer'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end
